name: Synchronize Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the Code Repository
      uses: actions/checkout@v3
      with:
        path: code

    - name: Run Sidebar Script
      run: |
        cd code/docs
        bash ../update_sidebar.sh # Ejecuta el script para actualizar _Sidebar.md

    - name: Clone the Wiki Repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://github.com/olmedokenpo/demo-wiki.wiki.git wiki

    - name: Clean the Wiki Content
      run: |
        rm -rf wiki/* # Elimina todo el contenido en el directorio wiki antes de agregar los nuevos archivos

    - name: Synchronize Wiki Content
      run: |
        rsync -av --delete --exclude '.git' code/docs/* wiki/

    - name: Commit and Push to the Wiki
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd wiki
        git config user.name github-actions
        git config user.email github-actions@github.com
        git config --global credential.helper store  
        git add -A
        git commit -m "Update wiki from code repository" || echo "There are no changes to commit."
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/olmedokenpo/demo-wiki.wiki.git
