name: Sincronizar Wiki

on:
  push:
    branches:
      - main  # Ajusta esto a la rama que utilizas

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del Repositorio de Código
      uses: actions/checkout@v3
      with:
        path: code

    - name: Clonar Repositorio de la Wiki con Git manualmente
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone --verbose --branch=main --single-branch https://x-access-token:${GITHUB_TOKEN}@github.com/olmedokenpo/demo-wiki.wiki.git wiki
        
    - name: Copiar Contenido de la Wiki
      run: |
        cp -a code/docs/. wiki/

    - name: Commit y Push a la Wiki
      run: |
        cd wiki
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Actualizar wiki desde el repositorio de código" || echo "No hay cambios para commit"
        git push
